# Generated by Django 5.2.14 on 2026-05-17 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AT_PORTER', 'At Porter'), ('WITH_STUDENT', 'With Student')], default='AT_PORTER', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_actions', to=settings.AUTH_USER_MODEL)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='key_status', to='hostels.room')),
            ],
            options={
                'verbose_name_plural': 'Key statuses',
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_id', models.CharField(max_length=100, unique=True)),
                ('hostel', models.CharField(max_length=100)),
                ('action_type', models.CharField(choices=[('DROP', 'Drop Key'), ('COLLECT', 'Collect Key')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['hostel', 'action_type'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('hostel', 'action_type'), name='unique_active_qr_per_hostel_action')],
            },
        ),
        migrations.CreateModel(
            name='KeyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('DROP', 'Drop Key'), ('COLLECT', 'Collect Key')], max_length=10)),
                ('resulting_status', models.CharField(choices=[('AT_PORTER', 'At Porter'), ('WITH_STUDENT', 'With Student')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='hostels.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_activities', to=settings.AUTH_USER_MODEL)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='keys.qrcode')),
            ],
            options={
                'verbose_name_plural': 'Key activities',
                'ordering': ['-timestamp'],
            },
        ),
    ]
